### ISSUE TITLE
どういう風に使えばいいですか？

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/discussions-ja#1]
詳しい使い方とか決まってますか？

**Comment by sugitach** [comment]
nodeschool の workshop を実行してて、わからないことがあったら、それを誰かわかる人に尋ねるのに使ってください。

今、英語版の discussions の README を翻訳してます。細かいことはそれができたらわかってもらえると思います。(^^;

**Comment by sotayamashita** [comment]
了解です！！
