### ISSUE TITLE
learnyounode 3:my_first_io

### ISSUE THREAD

**Issue by sugitach** [nodeschool/discussions-ja#3]
昨日のnodeschool-osakaで何人かの人が悩んでいた問題。
- 「ファイルシステムの関数を使ってファイルの改行数を出すアプリを書いてください。」
- 「 Write a program that uses a single **synchronous** filesystem operation to read a file and print the number of newlines it contains to the console (stdout)」

英語だと明快なんだけど、日本語だとちょっとわかりづらい。
要するに「改行コードの数」を数えないといけなかったんですねぇ。。。

しかも、 'cat FILE | wc -l' も、同じように改行コードの数を数えている様子。てっきり行数を数えているのだと思い込んでいました。

```
echo '1\n2\n3' | wc -l    → 2
echo '1\n2\n3\n' | wc -l  → 3
```

になります。。。

**Comment by marocchino** [comment]
改行文字(`\n`)とかでどうでしょう？

**Comment by sugitach** [comment]
そうですよね。日本語ならその辺りが妥当なんじゃないかと思います。

**Comment by marocchino** [comment]
この[コミット](https://github.com/workshopper/learnyounode/commit/ab56459e98aca130595aef3d7d14907970034a34)を見ると他の国にもあったようですね。

**Comment by sugitach** [comment]
お、ほんとですね。じゃぁ、日本語も修正してプルリク出しときますか

## 

杉田 敏典 : SUGITA, Toshinori
sugitach@gmail.com
2015/05/24 午前11:59 "marocchino" notifications@github.com:

**Comment by marocchino** [comment]
あ、もう出しました。 workshopper/learnyounode#300

**Comment by sugitach** [comment]
おお、早い。ありがとうございます。じゃぁ、このissueも閉じときます。
